# Generated by Django 2.1.3 on 2018-12-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('PID', models.IntegerField(primary_key=True, serialize=False)),
                ('PName', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MyBaseUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('right', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('RID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('PName', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('price', models.FloatField(default=0)),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='sell',
            fields=[
                ('SID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('PName', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
                ('price', models.FloatField()),
                ('Time', models.DateTimeField()),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SuppID', models.IntegerField(primary_key=True, serialize=False)),
                ('Suppname', models.CharField(max_length=100)),
                ('Suppaddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PName', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('num', models.IntegerField()),
                ('Time', models.DateTimeField()),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Goods')),
                ('SuppID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('BID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Branch_id', serialize=False, to='accounts.MyBaseUser')),
                ('Bname', models.CharField(max_length=100)),
                ('Baddress', models.CharField(max_length=100)),
                ('Tel', models.IntegerField()),
                ('StaNO', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Client_id', serialize=False, to='accounts.MyBaseUser')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('StaNO', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Stuff_id', serialize=False, to='accounts.MyBaseUser')),
                ('SPassword', models.CharField(max_length=20)),
                ('StaName', models.CharField(max_length=20)),
                ('Position', models.CharField(max_length=20)),
                ('BID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Branch')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='BID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Supplier'),
        ),
        migrations.AddField(
            model_name='store',
            name='PID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Goods'),
        ),
        migrations.AddField(
            model_name='repository',
            name='SuppID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Supplier'),
        ),
        migrations.AddField(
            model_name='supply',
            name='BID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Branch'),
        ),
        migrations.AddField(
            model_name='supply',
            name='SMID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('BID', 'PID')},
        ),
        migrations.AddField(
            model_name='sell',
            name='BID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Branch'),
        ),
        migrations.AddField(
            model_name='sell',
            name='StaNO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('SuppID', 'PID')},
        ),
        migrations.AddField(
            model_name='record',
            name='BID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Branch'),
        ),
        migrations.AddField(
            model_name='record',
            name='CID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer'),
        ),
        migrations.AlterUniqueTogether(
            name='supply',
            unique_together={('SuppID', 'SMID', 'PID')},
        ),
    ]
